server:
  port: 8081

spring:
  security:
    user:
      name: root
      password: root
  thymeleaf:
    cache: false
  #    suffix: .html # 这是默认设置，所以不需要加 ".html"

  # Content-Type 为 application/json, @JsonFormat(优先级高) 或 spring.jackson.date-format
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  # Content-Type 为 application/x-www-form-urlencoded（普通表单上传）spring.mvc.format.date-time(优先级高) 或 @DatetimeFormat
  mvc:
    format:
      date-time: yyyy-MM-dd HH:mm:ss
    converters:
      preferred-json-mapper: gson

  redis: #配置redis
    host: 10.8.3.112
    database: 3
    port: 6379
    password:
    timeout: 5000 #连接超时时间
    jedis:
      pool:
        max-active: 8 #最大连接数。 使用负值表示无限制
        max-wait: -1 #当池耗尽时，在抛出异常之前，连接阻塞的最大时间。 使用负值无限阻塞
        max-idle: 8 #最大空闲连接数
        min-idle: 0 #最小空闲连接数
        time-between-eviction-runs: 60000 #每ms运行一次空闲连接回收器

hale:
  enable: true
  name: zang
  age: 199